--Single Column Index

CREATE INDEX IX_EMPID_EMPLOYEE ON EMPLOYEE(EMPLOYEEID)


--COMPOSITE INDEX - MULTI COLUMN INDEX

CREATE INDEX IX_EMPID_DEPTID_EMPLOYEE ON EMPLOYEE(EMPLOYEEID, DEPTID)

--IMPLICIT INDEXES - 1.UNIQUE AND 2.PRIMARY
--UNIQUE INDEX - THIS GETS CREATED WHEN WE APPLY UNIQUE CONSTRAIN ON EMAILID COLOUMN
CREATE UNIQUE INDEX IX_EMAIL_EMPLOYEE ON EMPLOYEE(EMAILID)